import { supabase } from '@/integrations/supabase/client';
import { Tables, TablesInsert } from '@/integrations/supabase/types';

type MedicalRecord = Tables<'medical_records'>;
type Prescription = Tables<'prescriptions'>;
type LabResult = Tables<'lab_results'>;
type Patient = Tables<'patients'>;
type Profile = Tables<'profiles'>;

export interface MedicalRecordWithDetails extends MedicalRecord {
  patient?: Pick<Patient, 'patient_id' | 'first_name' | 'last_name'>;
  doctor?: Pick<Profile, 'first_name' | 'last_name'>;
}

export const medicalRecordService = {
  async getAll(filters?: { patientId?: string; doctorId?: string }): Promise<MedicalRecordWithDetails[]> {
    // First fetch records with patient info
    let query = supabase.from('medical_records').select(`
      *,
      patient:patients!medical_records_patient_id_fkey(patient_id, first_name, last_name)
    `);
    
    if (filters?.patientId) {
      query = query.eq('patient_id', filters.patientId);
    }
    
    if (filters?.doctorId) {
      query = query.eq('doctor_id', filters.doctorId);
    }
    
    const { data, error } = await query.order('visit_date', { ascending: false });
    
    if (error) throw error;
    
    // Fetch doctor profiles for records that have doctor_id
    const doctorIds = [...new Set((data || []).map(r => r.doctor_id).filter(Boolean))];
    let doctorMap: Record<string, { first_name: string; last_name: string }> = {};
    
    if (doctorIds.length > 0) {
      const { data: doctors } = await supabase
        .from('profiles')
        .select('id, first_name, last_name')
        .in('id', doctorIds);
      
      doctorMap = (doctors || []).reduce((acc, d) => {
        acc[d.id] = { first_name: d.first_name, last_name: d.last_name };
        return acc;
      }, {} as Record<string, { first_name: string; last_name: string }>);
    }
    
    return (data || []).map(record => ({
      ...record,
      doctor: record.doctor_id ? doctorMap[record.doctor_id] : undefined,
    })) as MedicalRecordWithDetails[];
  },

  async getById(id: string): Promise<MedicalRecord | null> {
    const { data, error } = await supabase
      .from('medical_records')
      .select('*')
      .eq('id', id)
      .maybeSingle();
    
    if (error) throw error;
    return data;
  },

  async create(data: Omit<TablesInsert<'medical_records'>, 'record_id'>): Promise<MedicalRecord> {
    // record_id is auto-generated by trigger - don't pass it
    const { data: newRecord, error } = await supabase
      .from('medical_records')
      .insert(data as TablesInsert<'medical_records'>)
      .select()
      .single();
    
    if (error) throw error;
    return newRecord;
  },

  async update(id: string, data: Partial<MedicalRecord>): Promise<MedicalRecord | null> {
    // Get current version
    const { data: current } = await supabase
      .from('medical_records')
      .select('version')
      .eq('id', id)
      .single();
    
    const { data: updated, error } = await supabase
      .from('medical_records')
      .update({
        ...data,
        version: (current?.version || 0) + 1,
        previous_version_id: id,
      })
      .eq('id', id)
      .select()
      .single();
    
    if (error) throw error;
    return updated;
  },

  async getPrescriptions(medicalRecordId: string): Promise<Prescription[]> {
    const { data, error } = await supabase
      .from('prescriptions')
      .select('*')
      .eq('medical_record_id', medicalRecordId);
    
    if (error) throw error;
    return data || [];
  },

  async addPrescription(data: TablesInsert<'prescriptions'>): Promise<Prescription> {
    const { data: newPrescription, error } = await supabase
      .from('prescriptions')
      .insert(data)
      .select()
      .single();
    
    if (error) throw error;
    return newPrescription;
  },

  async getLabResults(medicalRecordId: string): Promise<LabResult[]> {
    const { data, error } = await supabase
      .from('lab_results')
      .select('*')
      .eq('medical_record_id', medicalRecordId);
    
    if (error) throw error;
    return data || [];
  },

  async addLabResult(data: TablesInsert<'lab_results'>): Promise<LabResult> {
    const { data: newLabResult, error } = await supabase
      .from('lab_results')
      .insert(data)
      .select()
      .single();
    
    if (error) throw error;
    return newLabResult;
  },

  async getPatientHistory(patientId: string): Promise<{
    records: MedicalRecord[];
    prescriptions: Prescription[];
    labResults: LabResult[];
  }> {
    const { data: records } = await supabase
      .from('medical_records')
      .select('*')
      .eq('patient_id', patientId)
      .order('visit_date', { ascending: false });
    
    const recordIds = records?.map(r => r.id) || [];
    
    let prescriptions: Prescription[] = [];
    let labResults: LabResult[] = [];
    
    if (recordIds.length > 0) {
      const { data: prescs } = await supabase
        .from('prescriptions')
        .select('*')
        .in('medical_record_id', recordIds);
      prescriptions = prescs || [];
      
      const { data: labs } = await supabase
        .from('lab_results')
        .select('*')
        .in('medical_record_id', recordIds);
      labResults = labs || [];
    }
    
    return {
      records: records || [],
      prescriptions,
      labResults,
    };
  },
};
