import { supabase } from '@/integrations/supabase/client';
import { Tables, TablesInsert, TablesUpdate } from '@/integrations/supabase/types';

type Patient = Tables<'patients'>;
type PatientInsert = TablesInsert<'patients'>;
type PatientUpdate = TablesUpdate<'patients'>;

export const patientService = {
  async getAll(filters?: { search?: string; status?: string }): Promise<Patient[]> {
    let query = supabase.from('patients').select('*');
    
    if (filters?.status) {
      query = query.eq('status', filters.status);
    }
    
    const { data, error } = await query.order('created_at', { ascending: false });
    
    if (error) throw error;
    
    let result = data || [];
    
    if (filters?.search) {
      const searchLower = filters.search.toLowerCase();
      result = result.filter(p => 
        p.first_name.toLowerCase().includes(searchLower) ||
        p.last_name.toLowerCase().includes(searchLower) ||
        p.patient_id.toLowerCase().includes(searchLower) ||
        p.phone.includes(filters.search!) ||
        (p.email && p.email.toLowerCase().includes(searchLower))
      );
    }
    
    return result;
  },

  async getById(id: string): Promise<Patient | null> {
    const { data, error } = await supabase
      .from('patients')
      .select('*')
      .eq('id', id)
      .maybeSingle();
    
    if (error) throw error;
    return data;
  },

  async create(data: Omit<PatientInsert, 'patient_id'>): Promise<Patient> {
    // patient_id is auto-generated by trigger - don't pass it
    const { data: newPatient, error } = await supabase
      .from('patients')
      .insert(data as PatientInsert)
      .select()
      .single();
    
    if (error) throw error;
    return newPatient;
  },

  async update(id: string, data: PatientUpdate): Promise<Patient | null> {
    const { data: updated, error } = await supabase
      .from('patients')
      .update(data)
      .eq('id', id)
      .select()
      .single();
    
    if (error) throw error;
    return updated;
  },

  async delete(id: string): Promise<boolean> {
    const { error } = await supabase
      .from('patients')
      .delete()
      .eq('id', id);
    
    if (error) throw error;
    return true;
  },
};
